### ISSUE TITLE
"Edit Series" mode causes the series plot and Y-axis to change 

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODMToolsPython#271]
Selected the series, and before editing, the series looks like this:
![before edit](https://cloud.githubusercontent.com/assets/12566275/15228132/db8a37e8-1847-11e6-8328-2b5a1fd29e44.JPG)

Then when I click "Edit Series", the plots Y-Axis range increases dramatically and most of the values in the plot change to zero. It looks like this:
![after edit](https://cloud.githubusercontent.com/assets/12566275/15228162/09dd0d82-1848-11e6-99d4-b184ec8cde1e.JPG)

Even when I zoom, the plot does not visually display what the values actually are. 
![afterzoom](https://cloud.githubusercontent.com/assets/12566275/15228227/59241f84-1848-11e6-974f-e61a39d240c1.JPG)

This error only occurs for some of the series values, such as seriesID 878. But for some, the edit plot looks as it should, such as in the image below
![works](https://cloud.githubusercontent.com/assets/12566275/15228905/a4d04f36-184b-11e6-9865-1bd5755291f7.JPG)

**Comment by horsburgh** [comment]
This is by design.  When you enter edit mode, the NoData values are plotted so they can be edited if needed. The other values don't really get set to 0 - they are just so much smaller in magnitude than the NoData value that they look like they are zero until the NoData values are deleted or interpolated. If you continued to zoom in, you would see them separate from 0 on the y axis scale.

**Comment by PhilSuiter** [comment]
Oh I understand. I was confused because the series that I have normally been testing didn't do that, they all looked like the last image.  Okay I'll close this issue then

**Comment by sreeder** [comment]
Are the values no data values? What values do you see when you look at the data table?



-Stephanie


-------- Original message --------
