### ISSUE TITLE
Qualifier Issue when Adding Points

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#278]
When using the Add Point form and adding qualifiers to the new points, the value is populated with a string when it should be a number. When you try and save, there is a database type issue.

![image](https://cloud.githubusercontent.com/assets/5023186/15342091/1264c7d6-1c50-11e6-99dc-874d2e219cf4.png)

**Comment by sreeder** [comment]
@AmberSJones  this issue is ready for testing on the qualid branch. but I am not setting it up to merge yet because there are still some issues with some of the values when saving. the new row saves fine but the default values are set to nan. let me know if that is normal.

![screen shot 2016-06-06 at 3 56 45 pm](https://cloud.githubusercontent.com/assets/4721940/15878092/791f1d7e-2cd5-11e6-81e6-4461a15aa0c4.png)

**Comment by AmberSJones** [comment]
The behavior is as expected for me on qualid brach. I am not seeing the nan that you posted in the screenshot @sreeder . I'm closing the issue.
