### ISSUE TITLE
Is this project superseded by ODM2/ODM2?

### ISSUE THREAD

**Issue by ppoyk** [ODM2/ODMToolsPython#330]
I have seen no clear evidence around the project which would indicate that this would be superseded by other versions, but I also found the ODM2/ODM2 repository. Based on the update dates the former would seem to be more up-to-date.

If this is the case, could the information about the project deprecation / replacement by ODM2/ODM2 be added clearly to the top of the README of this project?

**Comment by horsburgh** [comment]
@ppoyk - to answer your question, no the ODM2 repo doesn't supersede the ODMToolsPython software or this repo. The ODM2/ODM2 repository contains the ODM2 information model and implementation for relational database management systems. This repository contains a software for working with time series data (e.g., visualization and quality control) stored in an ODM database. I believe it works with both ODM1 and ODM2, but it's been a while since we actively worked on this.
